### ISSUE TITLE
Not Counting

### ISSUE THREAD

**Issue by jairus0893** [BstName/every-click-counts#1] opened 2016-03-31 23:25 UTC
Hi @BstName Thank u first for ur help that solves my issue..  and about this plugin u created i got an issue i follow all ur steps i revert functions.php but again this not count multiple click.. Thanks

**Comment by BstName** [comment] 2016-04-01 07:48
Hi, thanks for testing, and for reporting the issue! 

I just tested it again, and all works just fine on my side. 

Would you fancy doing another test? Please do the following: 
1. Under 'Manage Plugins' in your admin panel, please temporarily deactivate all other plugins, except for 'Every Click Counts', which must be activated (i.e. listed in bold font).
2. Create a **new** short URL in the admin panel
3. Give the new short URL a few clicks (either by visiting it in a new browser tab, i.e. by typing or cutting&pasting 'http://{your-yourls-domain.tld}/{short URL}' in/to your browser bar; or by clicking the link in the column 'Short URL' in the respective row in the table in your admin panel a few times, thereby hitting the 'Back' button of your browser every time to return to the admin panel).
4. Now refresh(!) the admin panel's page (i.e. hit CTRL F5). You should now see a number of clicks greater than one in the 'Clicks' column of the respective row in your admin panel.

Please let me first know whether this works for you. 

Further explanation:
By (1) we make sure that no other plugin is causing the problems.
By (2) we make sure that the current issue is not just caused by your browser cache, which may still be polluted by previously cached HTTP 301 redirects for short URLs you had created, that is, before the issue had been fixed by the plugin (or by the temporary fix I had provided before). That is, the plugin does not empty the browser cache, it just prevents further pollution of the cache after it has been activated.

Please let me know about the results.

**Comment by jairus0893** [comment] 2016-04-04 06:13
yes sorry for my late feedback.. i follow your steps. and it works!! Great.. THanks

**Comment by BstName** [comment] 2016-04-04 08:35
Great, thanks for taking the time to test it again :+1:

And I am closing this issue now.

**Closed as completed by BstName** 2016-04-04 08:35 UTC
